name: OrganDonorApp
description: Organ Donor System
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_inner_drawer: ^1.0.0+1
  flutter_secure_storage: ^5.0.2
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  http: ^0.13.4
  intl: ^0.17.0
  provider: ^6.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
